# Generated by Django 3.1.3 on 2023-11-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('sector', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('quantity_served', models.FloatField(default=0)),
                ('is_consumable', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='request.request')),
            ],
            options={
                'verbose_name': 'Product Request',
                'verbose_name_plural': 'Products Requests',
            },
        ),
        migrations.RenameModel(
            old_name='Movement',
            new_name='MovementProduct',
        ),
        migrations.AlterModelOptions(
            name='movementproduct',
            options={'verbose_name': 'Movement Product', 'verbose_name_plural': 'Movements Products'},
        ),
        migrations.DeleteModel(
            name='Request_Product',
        ),
    ]
